<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>SimpleMACChanger</AssemblyName>
    <RootNamespace>SimpleMACChanger</RootNamespace>

    <ApplicationIcon>App.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management"
                      Version="8.0.0" />
  </ItemGroup>

</Project>
